version: '3.8'

services:
  downloader:
    build: .
    container_name: youtube_downloader
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
